os: linux
dist: focal
language: generic
vm: 
  create:
    name: checking_build
before_install:
  - sudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
script:
  - echo $TRAVIS_COMMIT_MESSAGE
  - echo "OKOK"
